### ISSUE TITLE
Support for white temperature?

### ISSUE THREAD

**Issue by MHeuvel** [mdaskalov/homebridge-tasmota-zbbridge#2]
Hi,
I have bought a light bulb with an option for the white color temperature but the device created does not expose a control for it. In the source code I don't see any commands for it? Am I missing anything?

**Comment by mdaskalov** [comment]
You can select "White Light with Dimmer and Cold/Warm White" in "ZbBridgeDevices" or configure "light2" as type in the configuration file.

**Comment by MHeuvel** [comment]
Yes, I did. But no control shows up in homebridge or the homekit app. In the source code zbBridgeAccessory.ts I can't see any additional code for light2. For light3 I found settings for hue and saturation. I expected to find similar code for temperature for light2.

**Comment by mdaskalov** [comment]
You're right currently it's actually the same logic for light1 and light2 - as I have no such light I've forgotten to implement it...
I will do so in my next release. Shouldn't be difficult. You can test it and give me feedback.

**Comment by mdaskalov** [comment]
I've just published new release which should support color temperature. Please test and report if it works for you.

**Comment by MHeuvel** [comment]
Sure, I will try it out and report back.

Edited: the bulb is recognized in homekit as dimmable and white color temp, so that's good. But after the first command in tasmota on my zbbridge it shows up as RGB. But I was able to change from cool to warm but only to the max values instead of a specific temperature. Same as I tried to do that manually with MQTT so probably not a plugin issue.
I need to find out why my bulb shows up as RGB, maybe that will solve it.

Homebridge does not show a control for it. But since both Homekit and Google home assistant do, that's not an issue with this plugin either.

thanks for your quick update.

edit 2 - with ZbLight name,2 changed it from rgb to white.
Could it be that the min/max values are off? See:
https://tasmota.github.io/docs/Lights/

Manuallu sending MQTT messages I was able to control intermediate values.
153 reporting 6550K
220 reporting 4550K
330 reporting 3050K
410 reporting 2450K
500 reporting 2000K (below specified limit on the box)

hope that helps.

**Comment by mdaskalov** [comment]
The color temperature for the zigbee command is defined as 0..65534 [here](https://tasmota.github.io/docs/Zigbee/).

In homebridge the range is 140..500. I am mapping it accordingly. 

Can you confirm, that you can correctly control the temperature in the range 140..500 using following command

ZbSend { "device":"0x4773", "send":{"CT":153} }

If that's the case, I will remove the mapping and it should work correctly.

**Comment by MHeuvel** [comment]
Hi,

ZbSend { "device":"0xE98F", "send":{"CT":153} } Result in 6550K
ZbSend { "device":"0xE98F", "send":{"CT":253} } results in 3950K
ZbSend { "device":"0xE98F", "send":{"CT":375} } results in 2659K
ZbSend { "device":"0xE98F", "send":{"CT":500} } results in 2000K

last one should be below the lamp's limit of 2200K.

does this help?

edit: console log:
17:59:32 CMD: ZbSend { "device":"0xE98F", "send":{"CT":470} }
17:59:32 MQT: stat/zbbridge/RESULT = {"ZbSend":"Done"}
17:59:32 MQT: tele/zbbridge/RESULT = {"ZbResponse":{"Device":"0xE98F","Name":"Keuken","Command":"0300!0A","Status":0,"StatusMessage":"SUCCESS","Endpoint":1,"LinkQuality":79}}
17:59:32 MQT: tele/zbbridge/SENSOR = {"ZbReceived":{"0xE98F":{"Device":"0xE98F","Name":"Keuken","CT":470,"ColorMode":2,"Endpoint":1,"LinkQuality":76}}}
17:59:33 MQT: tele/zbbridge/SENSOR = {"ZbReceived":{"0xE98F":{"Device":"0xE98F","Name":"Keuken","Hue":0,"Sat":254,"X":45874,"Y":19660,"CT":470,"ColorMode":2,"Endpoint":1,"LinkQuality":76}}}

**Comment by mdaskalov** [comment]
Thanx. it seems that the mapping is no necessary, so I removed it and made another release. Please try again.

**Comment by MHeuvel** [comment]
Works fine! It appears your work is done. ;-)

**Comment by mdaskalov** [comment]
Then I'll close this.
