### ISSUE TITLE
After updating to 1.5.0 only one of two contact sensors works

### ISSUE THREAD

**Issue by crassmike** [mdaskalov/homebridge-tasmota-zbbridge#28]
**Describe Your Problem:**

I have problems with 2 contact sensors in my configuration. First they worked ok but recently I noticed one was stopping reporting state changes. So I removed both and added them again. Then just one was added as an accessory, completely ignoring the second one. Solution was to roll back to plugin version 1.4.4 and add the sensors again. Now it works all fine again. Updating to 1.5.0 brings back the issue. Hope you can fix it in upcoming versions! Otherwise it is a great plugin!

**Logs:**

[16/10/2022, 16:47:24] [ZbBridge] Executed didFinishLaunching callback
[16/10/2022, 16:47:24] [ZbBridge] MQTT subscribe: zigbee2mqtt/bridge/devices, m5ll9bgos2t
[16/10/2022, 16:47:24] [ZbBridge] MQTT: Published: cmnd/tasmota_E31E7B/zbname 0x00124B002512381C,Schlafzimmertür
[16/10/2022, 16:47:24] [ZbBridge] MQTT: Published: cmnd/tasmota_E31E7B/zbinfo 0x00124B002512381C
[16/10/2022, 16:47:24] [ZbBridge] Restoring zbBridge accessory: Schlafzimmertür (0x00124B002512381C) - sensor
…

**Plugin Config:**

            "zbBridgeDevices": [
                {
                    "addr": "0x00124B00251228FD",
                    "type": "sensor",
                    "name": "Wohnzimmertür",
                    "sensorService": "ContactSensor",
                    "sensorCharacteristic": "ContactSensorState",
                    "sensorValuePath": "Contact"
                },
                {
                    "addr": "0x00124B002512381C",
                    "type": "sensor",
                    "name": "Schlafzimmertür",
                    "sensorService": "ContactSensor",
                    "sensorCharacteristic": "ContactSensorState",
                    "sensorValuePath": "Contact"
                }
            ],

**Environment:**

* **Plugin Version**: 1.5.0
* **Homebridge Version**: v1.5.0
* **Node.js Version**:  v16.18.0
* **NPM Version**: 8.19.2
* **Operating System**: Raspbian

**Comment by mdaskalov** [comment]
With version 1.5.0 I introduced support for Zigbee2MQTT by adding a new zbBridge device type `z2m`. This turned out to be a mistake, as there is less in common between these two device types. As you might guess my setup now uses only Zigbee2MQTT and obviously I haven’t tested (enough) the old functionality... Sorry, about that.  

I am working currently on a new version, where the Zigbee2MQTT devices would be configured separately and will publish it in the next days. 

So please stay with the old release until I’m done.

**Comment by crassmike** [comment]
Ok, thank you for your reply! I'm looking forward to the new version.
I appreciate your work on the plugin!

**Comment by mdaskalov** [comment]
Just published v1.5.1
Hope that the problem is solved in it.

**Comment by crassmike** [comment]
Works with v1.5.1!
