### ISSUE TITLE
Adaptive lighting support

### ISSUE THREAD

**Issue by ZoneMR** [mdaskalov/homebridge-tasmota-zbbridge#36]
**Describe the solution you'd like:**
It would be great to support HomeKit Adaptive Lighting, in-line with similar homebridge plugins eg homebridge-mqtthing.

**Additional context:**
This would enable the colour temperature of lighting to change in-line with the time of day.

**Comment by mdaskalov** [comment]
Added in release v1.9.0 
please give feedback (and a star)!
