### ISSUE TITLE
Support for a Motion Sensor?

### ISSUE THREAD

**Issue by ChaotenKurt** [mdaskalov/homebridge-tasmota-zbbridge#4]
Hello, first of all great work so far.  What I am currently missing is the ability to add a Zigbee motion detector.  I currently have one from Sonoff (SNZB-03).  When a movement is detected, I get the following messages in the console:

18:27:59.008 ZIG: {"ZbEZSPReceived":"450000040100050101000000003B80BC7261FFFF0919DC00010000010000"}

18:27:59.011 ZIG: {"ZbZCLReceived":{"groupid":0,"clusterid":"0x0500","srcaddr":"0x6172","srcendpoint":1,"dstendpoint":1,"wasbroadcast":0,"LinkQuality":50,"securityuse":0,"seqnumber":59,"fc":"0x19","frametype":1,"direction":1,"disableresp":1,"manuf":"0x0000","transact":220,"cmdid":"0x00","payload":"010000010000"}}

18:27:59.014 ZIG: ZbZCLRawReceived: {"0x6172":{"0500<00":"010000010000","ZoneStatusChange":1,"ZoneStatusChangeZone":1,"0406/0000":1,"Endpoint":1,"LinkQuality":50}}

18:27:59.020 MQT: tele/tasmota_E30562/SENSOR = {"ZbReceived":{"0x6172":{"Device":"0x6172","Name":"Bewegungssensor","0500<00":"010000010000","ZoneStatusChange":1,"ZoneStatusChangeZone":1,"Occupancy":1,"Endpoint":1,"LinkQuality":50}}}

**Comment by mdaskalov** [comment]
Unfortunately your motion sensor is sending messages which are not parsed by Tasmota.
This makes it difficult to implement.

I am using a motion sensor from IKEA and get following message, when the power is activated:
```
17:43:29.588 MQT: tele/zbbridge/SENSOR = {"ZbReceived":{"0x01F3":{"Device":"0x01F3","Name":"MotionSensor","0006!42":"0058020000","Power":1,"PowerOnlyWhenOn":0,"PowerOnTime":60,"PowerOffWait":0,"Endpoint":1,"Group":57519,"LinkQuality":134}}}
```

One idea would be to bind your motion sensor to a light or switch and then include them to homebridge. 

As an alternative have a look at the [homebridge-mqttthing](https://github.com/arachnetech/homebridge-mqttthing) plugin where custom MQTT can be configured quite flexible. 

The main goal of my plugin was to combine Tasmota switches with Zigbee lightbulbs and do the range arithmetic automatic.

To support all possible ZigBee devices it will take much more effort...

**Comment by mdaskalov** [comment]
With the latest release the [OccupancySensor](https://developers.homebridge.io/#/service/OccupancySensor) can be used with following states (see [here](https://developers.homebridge.io/#/characteristic/OccupancyDetected)):
```
OCCUPANCY_NOT_DETECTED    0
OCCUPANCY_DETECTED        1
```
We will use the `Occupancy` value to detect `OCCUPANCY_DETECTED` and `OCCUPANCY_NOT_DETECTED` states.

The configuration should be:
```
{
    "addr": "0x6172",
    "type": "sensor_0x0500_0_OccupancySensor_OccupancyDetected_Occupancy",
    "name": "Bewegungssensor"
}
```
I assume that the current state could be read using cluster 0x500 / attribute 0 but I am not sure. 

For battery powered devices it’s anyway not possible to read the state as they are normally in sleep mode.

I am thinking about removing this in future releases.

**Comment by mdaskalov** [comment]
Now possible after #19. Also have a look at [Tasmota Zigbee device plugin mechanism](https://github.com/arendst/Tasmota/pull/16252) - will be in next release.
