### ISSUE TITLE
Can't connect to matt broker after updating to 1.9.0

### ISSUE THREAD

**Issue by Elvys8** [mdaskalov/homebridge-tasmota-zbbridge#42]
I've been avoiding the latest update because of the "Breaking changes" warning, but ultimately decided to try it today.
I did lose all of my devices (I'm just that clumsy), but didn't mind to add them again.
The problem is that the plugin doesn't seem to connect to my mqtt broker anymore, I get this message.

`[ZbBridge] MQTT: Error: getaddrinfo ENOTFOUND host
`

The hostname box in the setup is marked in red now, not sure why…
<img src="https://i.ibb.co/vmpKHhy/Captura-de-pantalla-2023-11-11-a-las-2-25-02.png" alt="screenshot">

Any help is welcome!!

**Environment:**

* **Plugin Version**: 1.9.0
* **Homebridge Version**: 1.4.1
* **Node.js Version**: v18.13.0
* **Operating System**: DSM 7.2-64570 Update 3

**Comment by mdaskalov** [comment]
Sorry! I haven't seen this fast enough to reply.. 
You probably found out what's the problem on your own - the port should not be added in the host field.
