### ISSUE TITLE
Support more than 4 Switches

### ISSUE THREAD

**Issue by ChaotenKurt** [mdaskalov/homebridge-tasmota-zbbridge#5]
Hello, would it be possible for me to control more than 4 different switches on a Tasmota device? I have an ESP32 with 16 switches. I'd like to be able to control them all.

**Comment by mdaskalov** [comment]
This shouldn't be a problem. Just configure the corresponding POWER1 .. POWER16 directly in the configuration file. 
For example:
```
{
    "topic": "sonoff-16ch",
    "type": "POWER8",
    "name": "MyDevice"
}
```

**Comment by ChaotenKurt** [comment]
Great, I tried it and it works wonderfully. Sometimes you can't come up with the simplest ideas. Thank you very much for the quick reply.
