### ISSUE TITLE
[Question] Is a Sonoff SNZB-04 ZigBee Wireless Door/Window Sensor supported?

### ISSUE THREAD

**Issue by bluefangs** [mdaskalov/homebridge-tasmota-zbbridge#6]
I plan to buy a sonoff zigbee bridge and flash it with tasmota. I already have a few sonoff mini switches that work via mqtt, integrating with homebridge via the Homebridge Mqttthing plugin.

Recently I came across [Sonoff SNZB-04 ZigBee Wireless Door/Window Sensor](https://www.amazon.in/Sonoff-SNZB-04-Wireless-Required-Included/dp/B08QC7QKYR/ref=sr_1_1?dchild=1&keywords=sonoff+door+sensor&qid=1618666062&sr=8-1)
and would like to buy a few of them. Since they do not have a direct Wifi connectivity, I will also need to buy their Zigbee bridge, which I will flash tasmota on.

My question is, after flashing tasmota on the bridge, how do I add the door sensor to this? Is there support for this specific model?

Thanks!

**Environment:**

* **Plugin Version**: Latest available
* **Homebridge Version**: Latest available
* **Node.js Version**: v14.16.0
* **NPM Version**: 6.14.11
* **Operating System**: Rasbian / Pi 3B+

**Comment by mdaskalov** [comment]
if you flash the sonoff ZBBridge with Tasmota you can pair it with any Zigbee device and control it with MQTT. Not all devices are supported with dedicated commands but you should be able to control any device using low-level commands. Have a look at [this](https://tasmota.github.io/docs/Zigbee/) page to get the idea.

My plugin uses MQTT to control both Zigbee and other Tasmota devices in one plugin. I use it to switch lamps on and off using shelly2.5 and then to dim and change the color using Zigbee. And you don't have to do the range math for each device as in the mqttthing plugin. Of course you can also control both types of devices separately. 

I think the door/window sensor could be controlled like a motion sensor. It depends which cluster is addressed. If nothing works you can also use rules to generate custom MQTT messages or pair your sensor with a device added to HomeKit.

I can recommend the sonoff ZBBridge because it uses WiFi and can be positioned anywhere. I disconnected my ikea tradfri und hue bridges and use now only the sonoff zbbridge. And also the price is unbeatable.

**Comment by bluefangs** [comment]
Thanks for the clarification! I can order them both today since the price - like you said, is unbeatable :) On the point that it could be set up as a motion sensor, I'm wondering how the open / close event will translate to that. Given that montion sensor will just trigger a single (same) event each time it detects motion while a door sensor on the other hand ideally triggers an open event and a closed event. Please correct me if I'm mistaken with this.

**Comment by mdaskalov** [comment]
My IKEA motion sensor sends "Power": 1 when motion is detected and after a minute "Power": 0. When bound to a lamp for example (cluster 6 = power) the command turns the light on and then off. The MQTT message looks like this:
```
18:50:34.293 MQT: tele/zbbridge/SENSOR = {"ZbReceived":{"0x01F3":{"Device":"0x01F3","Name":"MotionSensor","0006!42":"0058020000","Power":1,"PowerOnlyWhenOn":0,"PowerOnTime":60,"PowerOffWait":0,"Endpoint":1,"Group":57519,"LinkQuality":29}}}
```
I expect similar behavior from the window sensor. It will send on / off events when it's open / closed.

**Comment by bluefangs** [comment]
Ah its slowly beginning to make sense to me. Please bear with me while I ask more questions :)

Once the bridge receives an on / off event, what determines the type of device that appears inside of the home app? Would I still need to use a ["contact sensor"](https://github.com/arachnetech/homebridge-mqttthing/blob/master/docs/Accessories.md#contact-sensor) type of a device as indicated by [homebridge-mqttthing](https://github.com/arachnetech/homebridge-mqttthing) or will your module itself expose it?

**Comment by mdaskalov** [comment]
Currently I don't support [ContactSensor](https://developers.homebridge.io/#/service/ContactSensor) type of service. So you will have to add it as a simple switch.
It shouldn't be a big deal to add this type of service - there is only a "get" event to be implemented.

**Comment by bluefangs** [comment]
I can try my hand at it. Would be my first contribution to a homebridge plugin.

Is [this](https://github.com/mdaskalov/homebridge-tasmota-zbbridge/blob/master/src/tasmotaAccessory.ts) the only file that requires to be updated? Can you please check the [changes](https://github.com/bluefangs/homebridge-tasmota-zbbridge/pull/1/commits/627969d3c2b140d8a59c039358e3d40e755352c0) I've made locally?

**Comment by ChaotenKurt** [comment]
Hello, I'm also currently trying to teach in the Sonoff temperature sensor and contact sensor. In my Sonoff Bridge with Tasmota, the devices were recognized immediately. The following is indicated in the bridge in the console if something changes in the temperature.

If I may ask, what should I change where so that it could work?

13:24:26.329 ZIG: {"ZbEZSPReceived":"45000004010204010100010000C528A6D019FFFF08185D0A0000298A09"} 13:24:26.331 ZIG: {"ZbZCLReceived":{"groupid":0,"clusterid":"0x0402","srcaddr":"0x19D0","srcendpoint":1,"dstendpoint":1,"wasbroadcast":0,"LinkQuality":0,"securityuse":0,"seqnumber":197,"fc":"0x18","frametype":0,"direction":1,"disableresp":1,"manuf":"0x0000","transact":93,"cmdid":"0x0A","payload":"0000298A09"}} 13:24:26.333 ZIG: ZbZCLRawErhalten: {"0x19D0":{"0402/0000":2442,"Endpunkt":1,"LinkQuality":0}} 13:24:26.733 MQT: tele/tasmota_E30562/SENSOR = {"ZbReceived":{"0x19D0":{"Gerät":"0x19D0","Name":"Sonoff Temp Sensor","Temperature":24.42,"Endpoint":1,"LinkQuality":0}}} 13:24:56.419 ZIG: {"ZbEZSPReceived":"45000004010204010100010000C71CA3D019FFFF08185E0A0000290B09"} 13:24:56.421 ZIG: {"ZbZCLReceived":{"groupid":0,"clusterid":"0x0402","srcaddr":"0x19D0","srcendpoint":1,"dstendpoint":1,"wasbroadcast":0,"LinkQuality":0,"securityuse":0,"seqnumber":199,"fc":"0x18","frametype":0,"direction":1,"disableresp":1,"manuf":"0x0000","transact":94,"cmdid":"0x0A","payload":"0000290B09"}} 13:24:56.423 ZIG: ZbZCLRawEmpfangen: {"0x19D0":{"0402/0000":2315,"Endpunkt":1,"LinkQuality":0}} 13:24:56.821 MQT: tele/tasmota_E30562/SENSOR = {"ZbReceived":{"0x19D0":{"Gerät":"0x19D0","Name":"Sonoff Temp Sensor","Temperature":23.15,"Endpoint":1,"LinkQuality":0}}}


13:29:17.673 MQT: tele/tasmota_E30562/SENSOR = {"ZbReceived":{"0x19D0":{"Device":"0x19D0","Name":"Sonoff Temp Sensor","Humidity":58.35,"Endpoint":1,"LinkQuality":0}}}

**Comment by mdaskalov** [comment]
Currently I only support switches and bulbs in the [zbBridgeAccessory.ts](https://github.com/mdaskalov/homebridge-tasmota-zbbridge/blob/master/src/zbBridgeAccessory.ts) file. I could extend this, but currently I don't have hardware to test it.

Another option would be to configure it as Tasmota Device and enter the MQTT path directly. Something like this could do the trick in your case:
```
"tasmotaDevices": [
        {
            "topic": "tasmota_E30562",
            "type": "ZbReceived.0x19D0.Temperature",
            "name": "Temperature"
        },
       {
            "topic": "tasmota_E30562",
            "type": "ZbReceived.0x19D0.Humidity",
            "name": "Humidity"
        }
...
]
```
You can also try the ```status 10``` command to find out the correct path (the ```type``` setting above) my sonoff TH module answers:
```
15:42:56.865 MQT: stat/sonoff/STATUS10 = {"StatusSNS":{"Time":"2021-04-18T15:42:56","AM2301":{"Temperature":23.4,"Humidity":38.0,"DewPoint":8.2},"TempUnit":"C"}}
```
so I have it configured as:
```
        {
            "topic": "sonoff",
            "type": "StatusSNS.AM2301.Temperature",
            "name": "Temperatur"
        },
        {
            "topic": "sonoff",
            "type": "StatusSNS.AM2301.Humidity",
            "name": "Rel. Feuchte"
        },
```
If temperature or humidity is detected in the path the appropriate sensor is created in homebridge.

**Comment by bluefangs** [comment]
@mdaskalov , I'm sorry I'm a bit confused. Your previous response was with reference to what @ChaotenKurt asked? Does it also hold good for the ContactSensor implementation as well? ContactSensor will use ZigBee to communicate and hence will also fall under "zbBridgeDevices", correct?

If lack of hardware is a bottleneck  for implementation, I am ready to assist you with whatever is required from my end! If you could guide me on what needs to be added to the `zbBridgeAccessory.ts` file, I can get to it!

Thanks.

**Comment by bluefangs** [comment]
Will this help with the cluster identification? It’s the exact device. 
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3036

**Comment by mdaskalov** [comment]
this doesn't help much. could you please send me some examples of the MQTT messages you get when it gets open or closed. I will try to implement it at the weekend.

**Comment by ChaotenKurt** [comment]
I hope this helps a little, I just noted from the console (Tasmota-Sonoff Zigbeebridge) yesterday.

`06:08:08.334 ZIG: {"ZbZCLReceived":{"groupid":0,"clusterid":"0x0500","srcaddr":"0x771D","srcendpoint":1,"dstendpoint":1,"wasbroadcast":0,"LinkQuality":0,"securityuse":0,"seqnumber":47,"fc":"0x19","frametype":1,"direction":1,"disableresp":1,"manuf":"0x0000","transact":24,"cmdid":"0x00","payload":"010000000000"}}
06:08:08.337 ZIG: ZbZCLRawReceived: {"0x771D":{"0500<00":"010000000000","ZoneStatusChange":1,"0500/FFF2":1,"Endpoint":1,"LinkQuality":0}}
06:08:08.343 MQT: tele/tasmota_E30562/SENSOR = {"ZbReceived":{"Sonoff Fensterkontakt":{"Device":"0x771D","Name":"Sonoff Fensterkontakt","0500<00":"010000000000","ZoneStatusChange":1,"Contact":1,"Endpoint":1,"LinkQuality":0}}}
06:08:15.059 ZIG: {"ZbEZSPReceived":"450000040100050101000000003024A51D77FFFF09191900000000000000"}
06:08:15.061 ZIG: {"ZbZCLReceived":{"groupid":0,"clusterid":"0x0500","srcaddr":"0x771D","srcendpoint":1,"dstendpoint":1,"wasbroadcast":0,"LinkQuality":0,"securityuse":0,"seqnumber":48,"fc":"0x19","frametype":1,"direction":1,"disableresp":1,"manuf":"0x0000","transact":25,"cmdid":"0x00","payload":"000000000000"}}
06:08:15.065 ZIG: ZbZCLRawReceived: {"0x771D":{"0500<00":"000000000000","ZoneStatusChange":0,"0500/FFF2":0,"Endpoint":1,"LinkQuality":0}}
06:08:15.071 MQT: tele/tasmota_E30562/SENSOR = {"ZbReceived":{"Sonoff Fensterkontakt":{"Device":"0x771D","Name":"Sonoff Fensterkontakt“,"0500<00":"000000000000","ZoneStatusChange":0,"Contact":0,"Endpoint":1,"LinkQuality":0}}}
`

**Comment by ChaotenKurt** [comment]
even if nobody asked, here is the log from the SONOFF SNZB-02 ZigBee Temperature And Humidity Sensor. Maybe it will be interesting or helpful later. :)

`21:34:26.759 ZIG: {"ZbEZSPReceived":"45000004010504010100010000C560B4D019FFFF0818DD0A000021D91D"}
21:34:26.760 ZIG: {"ZbZCLReceived":{"groupid":0,"clusterid":"0x0405","srcaddr":"0x19D0","srcendpoint":1,"dstendpoint":1,"wasbroadcast":0,"LinkQuality":29,"securityuse":0,"seqnumber":197,"fc":"0x18","frametype":0,"direction":1,"disableresp":1,"manuf":"0x0000","transact":221,"cmdid":"0x0A","payload":"000021D91D"}}
21:34:26.763 ZIG: ZbZCLRawReceived: {"0x19D0":{"0405/0000":7641,"Endpoint":1,"LinkQuality":29}}
21:34:27.161 MQT: tele/tasmota_E30562/SENSOR = {"ZbReceived":{"Test Temp":{"Device":"0x19D0","Name":"Test Temp","Humidity":76.41,"Endpoint":1,"LinkQuality":29}}}
21:34:29.814 ZIG: {"ZbEZSPReceived":"34000062"}
21:34:29.819 ZIG: {"ZbEZSPReceived":"3F0000FA84040106000101400100005F010000"}
`

`21:40:17.995 ZIG: {"ZbZCLReceived":{"groupid":0,"clusterid":"0x0402","srcaddr":"0x19D0","srcendpoint":1,"dstendpoint":1,"wasbroadcast":0,"LinkQuality":18,"securityuse":0,"seqnumber":203,"fc":"0x18","frametype":0,"direction":1,"disableresp":1,"manuf":"0x0000","transact":224,"cmdid":"0x0A","payload":"000029FC08"}}
21:40:17.998 ZIG: ZbZCLRawReceived: {"0x19D0":{"0402/0000":2300,"Endpoint":1,"LinkQuality":18}}
21:40:18.003 ZIG: {"ZbEZSPReceived":"45000004010504010100010000CD54B1D019FFFF0818E10A0000217523"}
21:40:18.005 ZIG: {"ZbZCLReceived":{"groupid":0,"clusterid":"0x0405","srcaddr":"0x19D0","srcendpoint":1,"dstendpoint":1,"wasbroadcast":0,"LinkQuality":21,"securityuse":0,"seqnumber":205,"fc":"0x18","frametype":0,"direction":1,"disableresp":1,"manuf":"0x0000","transact":225,"cmdid":"0x0A","payload":"0000217523"}}
21:40:18.008 ZIG: ZbZCLRawReceived: {"0x19D0":{"0405/0000":9077,"Endpoint":1,"LinkQuality":21}}
21:40:18.364 MQT: tele/tasmota_E30562/SENSOR = {"ZbReceived":{"Test Temp":{"Device":"0x19D0","Name":"Test Temp","Temperature":23,"Humidity":90.77,"Endpoint":1,"LinkQuality":21}}}
21:40:22.707 ZIG: {"ZbEZSPReceived":"45000004010600030100000000F638AAD3DCFFFF0718DB0A00001000"}
21:40:22.710 ZIG: {"ZbZCLReceived":`

**Comment by bluefangs** [comment]
OPEN STATE: 
```
18:54:27.543 ZIG: {"ZbEZSPReceived":"450000040100050101000100001BFFE53BF0FFFF09190E0001000001000002"}
18:54:27.545 ZIG: {"ZbZCLReceived":{"groupid":0,"clusterid":"0x0500","srcaddr":"0xF03B","srcendpoint":1,"dstendpoint":1,"wasbroadcast":0,"LinkQuality":157,"securityuse":0,"seqnumber":27,"fc":"0x19","frametype":1,"direction":1,"disableresp":1,"manuf":"0x0000","transact":14,"cmdid":"0x00","payload":"010000010000"}}
18:54:27.549 ZIG: ZbZCLRawReceived: {"0xF03B":{"0500<00":"010000010000","ZoneStatusChange":1,"ZoneStatusChangeZone":1,"0500/FFF2":1,"Endpoint":1,"LinkQuality":157}}
18:54:27.557 MQT: tele/tasmota_zbridge/SENSOR = {"ZbReceived":{"0xF03B":{"Device":"0xF03B","0500<00":"010000010000","ZoneStatusChange":1,"ZoneStatusChangeZone":1,"Contact":1,"Endpoint":1,"LinkQuality":157}}}
```
CLOSED STATE:
```
8:54:58.830 ZIG: {"ZbEZSPReceived":"450000040100050101000100001CFFE53BF0FFFF09190F0000000001000002"}
18:54:58.832 ZIG: {"ZbZCLReceived":{"groupid":0,"clusterid":"0x0500","srcaddr":"0xF03B","srcendpoint":1,"dstendpoint":1,"wasbroadcast":0,"LinkQuality":157,"securityuse":0,"seqnumber":28,"fc":"0x19","frametype":1,"direction":1,"disableresp":1,"manuf":"0x0000","transact":15,"cmdid":"0x00","payload":"000000010000"}}
18:54:58.835 ZIG: ZbZCLRawReceived: {"0xF03B":{"0500<00":"000000010000","ZoneStatusChange":0,"ZoneStatusChangeZone":1,"0500/FFF2":0,"Endpoint":1,"LinkQuality":157}}
18:54:58.841 MQT: tele/tasmota_zbridge/SENSOR = {"ZbReceived":{"0xF03B":{"Device":"0xF03B","0500<00":"000000010000","ZoneStatusChange":0,"ZoneStatusChangeZone":1,"Contact":0,"Endpoint":1,"LinkQuality":157}}}
```

**Comment by mdaskalov** [comment]
The `Contact` sensor is on cluster `0x500 / 0xFFF2`. 
The `Temperature` sensor is one cluster `0x405 / 0` and the `Humidity` sensor `0x402 / 0`. 

[Here](https://github.com/arendst/Tasmota/blob/0650744ac27108931a070918f08173d71ddfd68d/tasmota/xdrv_23_zigbee_5_converters.ino) you can find a list of all supported devices with their clusters.

We will need a generic configurable sensor accessory to cover all possibilities. We need to configure cluster, read command(s) and homebridge service type. I am thinking of something like:

```
sensor_0500_FFF2_MotionSensor
sensor_0405_0000_Temperature
sensor_0402_0000_Humidity
```

@bluefangs could you confirm that you can get the state with following command can read the sensor (please send me the answer):
```
ZbSend { "device": "0xF03B", "cluster": "0x500", "read": "0xFFF2" }
```

@ChaotenKurt could you confirm with following commands:
```
ZbSend { "device": "0x19D0", "cluster": "0x405", "read": 0 }
ZbSend { "device": "0x19D0", "cluster": "0x402", "read": 0 }
```

**Comment by bluefangs** [comment]
> The `Contact` sensor is on cluster `0x500 / 0xFFF2`.

> @bluefangs could you confirm that you can get the state with following command can read the sensor (please send me the answer):
> 
> ```
> ZbSend { "device": "0xF03B", "cluster": "0x500", "read": "0xFFF2" }
> ```


I ran the above command in the console and got this:

```
12:32:15.488 HTP: Console
12:32:40.128 CMD: ZbSend { "device": "0xF03B", "cluster": "0x500", "read": "0xFFF2" }
12:32:40.131 CMD: Group 0, Index 1, Command "ZBSEND", Data "{ "device": "0xF03B", "cluster": "0x500", "read": "0xFFF2" }"
12:32:40.134 ZIG: guessing endpoint 1
12:32:40.136 ZigbeeZCLSend device: 0xF03B, group: 0x0000, endpoint:1, cluster:0x0500, cmd:0x00, send:"F2FF"
12:32:40.137 ZIG: ZbEZSPSend 3400003BF004010005010140010000010105100100F2FF
12:32:40.141 MQT: stat/zbridge/RESULT = {"ZbSend":"Done"}
12:32:40.159 ZIG: {"ZbEZSPReceived":"3400003D"}
12:32:47.803 ZIG: {"ZbEZSPReceived":"8000423BF0"}
12:32:47.807 MQT: tele/zbridge/RESULT = {"ZbRouteError":{"ShortAddr":"0xF03B","Status":66,"StatusMessage":"MAC_INDIRECT_TIMEOUT"}}
12:32:57.037 ZIG: {"ZbEZSPReceived":"8000423BF0"}
12:32:57.041 MQT: tele/zbridge/RESULT = {"ZbRouteError":{"ShortAddr":"0xF03B","Status":66,"StatusMessage":"MAC_INDIRECT_TIMEOUT"}}
12:33:06.272 ZIG: {"ZbEZSPReceived":"8000423BF0"}
12:33:06.276 MQT: tele/zbridge/RESULT = {"ZbRouteError":{"ShortAddr":"0xF03B","Status":66,"StatusMessage":"MAC_INDIRECT_TIMEOUT"}}
12:33:07.867 ZIG: {"ZbEZSPReceived":"3F00003BF0040100050101400100003D016600"}
```

**Comment by mdaskalov** [comment]
seems that it was not reachable. try to send the command after you open / close the sensor.

**Comment by bluefangs** [comment]
The bridge is right next to me while the sensor is a room away. I"m able to get signals from the sensor while opening and closing the door. (Just tested a very simple automation with mqttthing and it seems to work.)

Here is my log dump indicating the working of the sensor but failing to respond to the `ZbSend` message 

```
7:47:40.426 ZIG: {"ZbEZSPReceived":"8000423BF0"}
17:47:40.430 MQT: tele/zbridge/RESULT = {"ZbRouteError":{"ShortAddr":"0xF03B","Status":66,"StatusMessage":"MAC_INDIRECT_TIMEOUT"}}
17:47:42.020 ZIG: {"ZbEZSPReceived":"3F00003BF00401000501014001000042016600"}
17:48:02.524 ZIG: {"ZbEZSPReceived":"450000040100050101000100000D28A63BF0FFFF0919F600010000000000"}
17:48:02.526 ZIG: {"ZbZCLReceived":{"groupid":0,"clusterid":"0x0500","srcaddr":"0xF03B","srcendpoint":1,"dstendpoint":1,"wasbroadcast":0,"LinkQuality":0,"securityuse":0,"seqnumber":13,"fc":"0x19","frametype":1,"direction":1,"disableresp":1,"manuf":"0x0000","transact":246,"cmdid":"0x00","payload":"010000000000"}}
17:48:02.529 ZIG: ZbZCLRawReceived: {"0xF03B":{"0500<00":"010000000000","ZoneStatusChange":1,"0500/FFF2":1,"Endpoint":1,"LinkQuality":0}}
17:48:02.534 MQT: tele/zbridge/F03B/SENSOR = {"ZbReceived":{"0xF03B":{"Device":"0xF03B","Name":"Back Door","0500<00":"010000000000","ZoneStatusChange":1,"Contact":1,"Endpoint":1,"LinkQuality":0}}}
17:48:05.460 ZIG: {"ZbEZSPReceived":"450000040100050101000100000E44AD3BF0FFFF0919F700000000000000"}
17:48:05.462 ZIG: {"ZbZCLReceived":{"groupid":0,"clusterid":"0x0500","srcaddr":"0xF03B","srcendpoint":1,"dstendpoint":1,"wasbroadcast":0,"LinkQuality":10,"securityuse":0,"seqnumber":14,"fc":"0x19","frametype":1,"direction":1,"disableresp":1,"manuf":"0x0000","transact":247,"cmdid":"0x00","payload":"000000000000"}}
17:48:05.465 ZIG: ZbZCLRawReceived: {"0xF03B":{"0500<00":"000000000000","ZoneStatusChange":0,"0500/FFF2":0,"Endpoint":1,"LinkQuality":10}}
17:48:05.471 MQT: tele/zbridge/F03B/SENSOR = {"ZbReceived":{"0xF03B":{"Device":"0xF03B","Name":"Back Door","0500<00":"000000000000","ZoneStatusChange":0,"Contact":0,"Endpoint":1,"LinkQuality":10}}}
17:48:28.083 CMD: ZbSend { "device": "0xF03B", "cluster": "0x500", "read": "0xFFF2" }
17:48:28.086 CMD: Group 0, Index 1, Command "ZBSEND", Data "{ "device": "0xF03B", "cluster": "0x500", "read": "0xFFF2" }"
17:48:28.091 ZigbeeZCLSend device: 0xF03B, group: 0x0000, endpoint:1, cluster:0x0500, cmd:0x00, send:"F2FF"
17:48:28.092 ZIG: ZbEZSPSend 3400003BF004010005010140010000070105100700F2FF
17:48:28.096 MQT: stat/zbridge/RESULT = {"ZbSend":"Done"}
17:48:28.115 ZIG: {"ZbEZSPReceived":"34000043"}
17:48:35.758 ZIG: {"ZbEZSPReceived":"8000423BF0"}
17:48:35.762 MQT: tele/zbridge/RESULT = {"ZbRouteError":{"ShortAddr":"0xF03B","Status":66,"StatusMessage":"MAC_INDIRECT_TIMEOUT"}}
17:48:44.994 ZIG: {"ZbEZSPReceived":"8000423BF0"}
17:48:44.998 MQT: tele/zbridge/RESULT = {"ZbRouteError":{"ShortAddr":"0xF03B","Status":66,"StatusMessage":"MAC_INDIRECT_TIMEOUT"}}
17:48:45.638 ZIG: {"ZbEZSPReceived":"4500000000388000004001000044FF000000FFFF1B000000F8FF071400130010D4DDB5B3D8C8CFD8C8EAA9D4C4D0F8D0"}
17:48:54.229 ZIG: {"ZbEZSPReceived":"8000423BF0"}
17:48:54.233 MQT: tele/zbridge/RESULT = {"ZbRouteError":{"ShortAddr":"0xF03B","Status":66,"StatusMessage":"MAC_INDIRECT_TIMEOUT"}}
17:48:55.825 ZIG: {"ZbEZSPReceived":"3F00003BF00401000501014001000043016600"}
...
...
...
17:56:42.136 CMD: ZbSend { "device": "0xF03B", "cluster": "0x500", "read": "0xFFF2" }
17:56:42.139 CMD: Group 0, Index 1, Command "ZBSEND", Data "{ "device": "0xF03B", "cluster": "0x500", "read": "0xFFF2" }"
17:56:42.144 ZigbeeZCLSend device: 0xF03B, group: 0x0000, endpoint:1, cluster:0x0500, cmd:0x00, send:"F2FF"
17:56:42.145 ZIG: ZbEZSPSend 3400003BF004010005010140010000080105100800F2FF
17:56:42.150 MQT: stat/zbridge/RESULT = {"ZbSend":"Done"}
17:56:42.169 ZIG: {"ZbEZSPReceived":"34000045"}
17:56:49.812 ZIG: {"ZbEZSPReceived":"8000423BF0"}
17:56:49.816 MQT: tele/zbridge/RESULT = {"ZbRouteError":{"ShortAddr":"0xF03B","Status":66,"StatusMessage":"MAC_INDIRECT_TIMEOUT"}}
17:56:59.047 ZIG: {"ZbEZSPReceived":"8000423BF0"}
17:56:59.051 MQT: tele/zbridge/RESULT = {"ZbRouteError":{"ShortAddr":"0xF03B","Status":66,"StatusMessage":"MAC_INDIRECT_TIMEOUT"}}
17:57:08.282 ZIG: {"ZbEZSPReceived":"8000423BF0"}
17:57:08.286 MQT: tele/zbridge/RESULT = {"ZbRouteError":{"ShortAddr":"0xF03B","Status":66,"StatusMessage":"MAC_INDIRECT_TIMEOUT"}}
17:57:09.877 ZIG: {"ZbEZSPReceived":"3F00003BF00401000501014001000045016600"}
```

**Comment by ChaotenKurt** [comment]
I received the first command in response
`
18:17:28.326 CMD: Group 0, Index 1, Command "ZBSEND", Data "{ "device": "0x19D0", "cluster": "0x405", "read": 0 }"
18:17:28.329 ZIG: guessing endpoint 1
18:17:28.331 ZigbeeZCLSend device: 0x19D0, group: 0x0000, endpoint:1, cluster:0x0405, cmd:0x00, send:"0000"
18:17:28.332 ZIG: ZbEZSPSend 340000D019040105040101400100000101051001000000
18:17:28.336 MQT: stat/tasmota_E30562/RESULT = {"ZbSend":"Done"}
18:17:28.361 ZIG: {"ZbEZSPReceived":"34000028"}
18:17:33.151 ZIG: {"ZbEZSPReceived":"3F0000D0190401050401014000000028016600"}
18:17:36.994 ZIG: {"ZbEZSPReceived":"5900BCF338C273FEFF9FFD9070B800"}
18:17:37.053 ZIG: {"ZbEZSPReceived":"450000040108000101000100003170B8BCF3FFFF0708310A0000200302"}
18:17:37.055 ZIG: {"ZbZCLReceived":{"groupid":0,"clusterid":"0x0008","srcaddr":"0xF3BC","srcendpoint":1,"dstendpoint":1,"wasbroadcast":0,"LinkQuality":39,"securityuse":0,"seqnumber":49,"fc":"0x08","frametype":0,"direction":1,"disableresp":0,"manuf":"0x0000","transact":49,"cmdid":"0x0A","payload":"00002003"}}
18:17:37.057 ZigbeeZCLSend device: 0xF3BC, group: 0x0000, endpoint:1, cluster:0x0008, cmd:0x0B, send:"0A00"
18:17:37.058 ZIG: ZbEZSPSend 340000BCF30401080001010000000031010510310B0A00
18:17:37.060 ZIG: ZbZCLRawReceived: {"0xF3BC":{"0008/0000":3,"Endpoint":1,"LinkQuality":39}}
18:17:37.070 ZIG: {"ZbEZSPReceived":"34000029"}
18:17:37.081 ZIG: {"ZbEZSPReceived":"3F0000BCF30401080001010000000029010000"}
18:17:37.433 MQT: tele/tasmota_E30562/SENSOR = {"ZbReceived":{"0xF3BC":{"Device":"0xF3BC","Name":"Ikea Lampe","Dimmer":3,"Endpoint":1,"LinkQuality":39}}}`

and that with the second command

`18:21:27.564 CMD: ZbSend { "device": "0x19D0", "cluster": "0x402", "read": 0 }
18:21:27.566 SRC: WebConsole from 192.168.2.14
18:21:27.568 CMD: Group 0, Index 1, Command "ZBSEND", Data "{ "device": "0x19D0", "cluster": "0x402", "read": 0 }"
18:21:27.571 ZIG: guessing endpoint 1
18:21:27.573 ZigbeeZCLSend device: 0x19D0, group: 0x0000, endpoint:1, cluster:0x0402, cmd:0x00, send:"0000"
18:21:27.574 ZIG: ZbEZSPSend 340000D019040102040101400100000201051002000000
18:21:27.578 MQT: stat/tasmota_E30562/RESULT = {"ZbSend":"Done"}
18:21:27.602 ZIG: {"ZbEZSPReceived":"3400002B"}
18:21:32.383 ZIG: {"ZbEZSPReceived":"3F0000D019040102040101400000002B016600"}`

**Comment by mdaskalov** [comment]
Seems that there is no possibility to "get" the state of a sensor... 
We will update it only when a SENSOR messages comes and return the last known status in the "onGet" event.
I've created a new branch 'zbbridge-sensor' for this...
To try it: checkout and then run:
```
npm run watch
```
configure it like this:
```
"zbBridgeDevices": [
        ...
        {
            "addr": "0xF03B",
            "type": "sensor_0x500_0xFFF2_ContactSensor_ContactSensorState_Contact",
            "name": "ContactSensor"
        },
        {
            "addr": "0x19D0",
            "type": "sensor_0x405_0_TemperatureSensor_CurrentTemperature_Temperature
            "name": "Temperature"
        },
        {
            "addr": "0x19D0",
            "type": "sensor_0x402_0_HumiditySensor_CurrentRelativeHumidity_Humidity",
            "name": "Humidity"
        }
    ]
```

**Comment by ChaotenKurt** [comment]
First of all, thank you very much for your efforts. I entered the data accordingly as described. However, the device is displayed as "not supported" in Home. The only thing I haven't gotten there yet, in the command "npm run watch". I entered this in the Homebridge console. But without success. See the pictures for this. (note: Hombridge runs in Docker on my Synology)
!

https://drive.google.com/drive/folders/1QIf7-XcaICQmTTPJgHtoDHIRoQIvwMiC?usp=sharing

**Comment by mdaskalov** [comment]
ah forget it... you had to install it on your local machine as described in the plugin template. To make it simple I just released new version with support for sensors.

**Comment by ChaotenKurt** [comment]
Perfect. Temperature and humidity are now displayed in home and are working. I will try the other one during the next few days. Thank you so much.

**Comment by ChaotenKurt** [comment]
Good morning, quick feedback on window contact. Unfortunately doesn't work for me, but I think it's the Sonoff in connection with Tasmota. In the console, I see that he doesn't send the status open or closed. I'll have to try the days there. If it's of interest, I'll just give you the data from the Sonoff motion sensor. Maybe you'll be able to take care of it.

`Bewegungssensor 0x5E8D (SONOFF SNZB-03)

Movement detected

ZIG: {"ZbEZSPReceived":"450000040100050101000100001F8CBF8D5EFFFF0919180001000000000002"}
ZIG: {"ZbZCLReceived":{"groupid":0,"clusterid":"0x0500","srcaddr":"0x5E8D","srcendpoint":1,"dstendpoint":1,"wasbroadcast":0,"LinkQuality":58,"securityuse":0,"seqnumber":31,"fc":"0x19","frametype":1,"direction":1,"disableresp":1,"manuf":"0x0000","transact":24,"cmdid":"0x00","payload":"010000000000"}}
ZIG: ZbZCLRawReceived: {"0x5E8D":{"0500<00":"010000000000","ZoneStatusChange":1,"0406/0000":1,"Endpoint":1,"LinkQuality":58}}
MQT: tele/tasmota_E30562/SENSOR = {„ZbReceived":{"0x5E8D":{"Device":"0x5E8D","0500<00":"010000000000","ZoneStatusChange":1,"Occupancy":1,"Endpoint":1,"LinkQuality":58}}}

Movement over

ZIG: {"ZbZCLReceived":{"groupid":0,"clusterid":"0x0500","srcaddr":"0x5E8D","srcendpoint":1,"dstendpoint":1,"wasbroadcast":0,"LinkQuality":55,"securityuse":0,"seqnumber":32,"fc":"0x19","frametype":1,"direction":1,"disableresp":1,"manuf":"0x0000","transact":25,"cmdid":"0x00","payload":"000000000000"}}
ZIG: ZbZCLRawReceived: {"0x5E8D":{"0500<00":"000000000000","ZoneStatusChange":0,"0406/0000":0,"Endpoint":1,"LinkQuality":55}}
MQT: tele/tasmota_E30562/SENSOR = {"ZbReceived":{"0x5E8D":{"Device":"0x5E8D","0500<00":"000000000000","ZoneStatusChange":0,"Occupancy":0,"Endpoint":1,"LinkQuality":55}}}
`

**Comment by mdaskalov** [comment]
It should be configured as service: `OccupancySensor`, characteristic: `OccupancyDetected`, path: `Occupancy` (see [here](https://developers.homebridge.io/#/service/OccupancySensor)) as follows:
```
       {
            "addr": "0x5E8D",
            "type": "sensor_0x500_0_OccupancySensor_OccupancyDetected_Occupancy",
            "name": "ContactSensor"
        }
```
...when I get some free time I will create definitions for all currently available sensors to make the configuration more user-friendly.

**Comment by ChaotenKurt** [comment]
thank you very much for your effort.

**Comment by mdaskalov** [comment]
Much easier with the latest release. See #19
